ALTER TABLE payments ADD COLUMN IF NOT EXISTS razorpay_order_id VARCHAR(255) UNIQUE;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS razorpay_payment_id VARCHAR(255) UNIQUE;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS razorpay_signature VARCHAR(255);
ALTER TABLE payments ALTER COLUMN payment_method DROP NOT NULL;
